In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head()
movies.columns.values
movies = movies[['id','title','genres','keywords','overview','tagline']]
movies.head()
movies.isna().sum()

id            0
title         0
genres        0
keywords      0
overview      3
tagline     844
dtype: int64

In [4]:
credits.head()
credits.rename(columns={'movie_id':'id'},inplace=True)
credits.drop(columns='title',inplace =True)
credits.head()

,id,cast,crew
0,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
movies.shape

(4803, 6)

In [6]:
credits.shape

(4803, 3)

In [7]:
df = movies.merge(credits,on='id')
df.head()

,id,title,genres,keywords,overview,tagline,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bondâ€™s past sends him o...,A Plan No One Escapes,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,The Legend Ends,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","Lost in our world, found in another.","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
df.loc[df['tagline'].isna(),'tagline'] = ''
df.loc[df['overview'].isna(),'overview'] = ''
df.isna().sum()

id          0
title       0
genres      0
keywords    0
overview    0
tagline     0
cast        0
crew        0
dtype: int64

In [9]:
import ast
def convert(obj) -> list:
    L =[]
    for i in ast.literal_eval(obj):
         L.append(i['name'])
    return ' '.join(L)

In [10]:
df.genres = df.genres.apply(convert)
df.keywords = df.keywords.apply(convert)
df

,id,title,genres,keywords,overview,tagline,cast,crew
0,19995,Avatar,Action Adventure Fantasy Science Fiction,culture clash future space war space colony so...,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,Adventure Fantasy Action,ocean drug abuse exotic island east india trad...,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,Action Adventure Crime,spy based on novel secret agent sequel mi6 bri...,A cryptic message from Bondâ€™s past sends him o...,A Plan No One Escapes,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Action Crime Drama Thriller,dc comics crime fighter terrorist secret ident...,Following the death of District Attorney Harve...,The Legend Ends,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,Action Adventure Science Fiction,based on novel mars medallion space travel pri...,"John Carter is a war-weary, former military ca...","Lost in our world, found in another.","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...
4798,9367,El Mariachi,Action Crime Thriller,united statesâ€“mexico barrier legs arms paper k...,El Mariachi just wants to play his guitar and ...,"He didn't come looking for trouble, but troubl...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,Newlyweds,Comedy Romance,,A newlywed couple's honeymoon is upended by th...,A newlywed couple's honeymoon is upended by th...,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"Signed, Sealed, Delivered",Comedy Drama Romance TV Movie,date love at first sight narration investigati...,"""Signed, Sealed, Delivered"" introduces a dedic...",,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,Shanghai Calling,,,When ambitious New York attorney Sam is sent t...,A New Yorker in Shanghai,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,My Date with Drew,Documentary,obsession camcorder crush dream girl,Ever since the second grade when he first saw ...,,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [11]:
def director(obj):
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            return i['name']
    return ''

def actors(obj):
    L =[]
    for i in ast.literal_eval(obj):
        if len(L) >=3:
            break
        else:
         L.append(i['name'])
    return ' '.join(L)

In [12]:
df.cast = df['cast'].apply(actors)
df.crew = df.crew.apply(director)
df

,id,title,genres,keywords,overview,tagline,cast,crew
0,19995,Avatar,Action Adventure Fantasy Science Fiction,culture clash future space war space colony so...,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,Sam Worthington Zoe Saldana Sigourney Weaver,James Cameron
1,285,Pirates of the Caribbean: At World's End,Adventure Fantasy Action,ocean drug abuse exotic island east india trad...,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.",Johnny Depp Orlando Bloom Keira Knightley,Gore Verbinski
2,206647,Spectre,Action Adventure Crime,spy based on novel secret agent sequel mi6 bri...,A cryptic message from Bondâ€™s past sends him o...,A Plan No One Escapes,Daniel Craig Christoph Waltz LÃ©a Seydoux,Sam Mendes
3,49026,The Dark Knight Rises,Action Crime Drama Thriller,dc comics crime fighter terrorist secret ident...,Following the death of District Attorney Harve...,The Legend Ends,Christian Bale Michael Caine Gary Oldman,Christopher Nolan
4,49529,John Carter,Action Adventure Science Fiction,based on novel mars medallion space travel pri...,"John Carter is a war-weary, former military ca...","Lost in our world, found in another.",Taylor Kitsch Lynn Collins Samantha Morton,Andrew Stanton
...,...,...,...,...,...,...,...,...
4798,9367,El Mariachi,Action Crime Thriller,united statesâ€“mexico barrier legs arms paper k...,El Mariachi just wants to play his guitar and ...,"He didn't come looking for trouble, but troubl...",Carlos Gallardo Jaime de Hoyos Peter Marquardt,Robert Rodriguez
4799,72766,Newlyweds,Comedy Romance,,A newlywed couple's honeymoon is upended by th...,A newlywed couple's honeymoon is upended by th...,Edward Burns Kerry BishÃ© Marsha Dietlein,Edward Burns
4800,231617,"Signed, Sealed, Delivered",Comedy Drama Romance TV Movie,date love at first sight narration investigati...,"""Signed, Sealed, Delivered"" introduces a dedic...",,Eric Mabius Kristin Booth Crystal Lowe,Scott Smith
4801,126186,Shanghai Calling,,,When ambitious New York attorney Sam is sent t...,A New Yorker in Shanghai,Daniel Henney Eliza Coupe Bill Paxton,Daniel Hsia
4802,25975,My Date with Drew,Documentary,obsession camcorder crush dream girl,Ever since the second grade when he first saw ...,,Drew Barrymore Brian Herzlinger Corey Feldman,Brian Herzlinger

In [13]:
df = df[['id','title','overview','tagline','genres','keywords','cast','crew']]
df

,id,title,overview,tagline,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,Action Adventure Fantasy Science Fiction,culture clash future space war space colony so...,Sam Worthington Zoe Saldana Sigourney Weaver,James Cameron
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.",Adventure Fantasy Action,ocean drug abuse exotic island east india trad...,Johnny Depp Orlando Bloom Keira Knightley,Gore Verbinski
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,A Plan No One Escapes,Action Adventure Crime,spy based on novel secret agent sequel mi6 bri...,Daniel Craig Christoph Waltz LÃ©a Seydoux,Sam Mendes
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,The Legend Ends,Action Crime Drama Thriller,dc comics crime fighter terrorist secret ident...,Christian Bale Michael Caine Gary Oldman,Christopher Nolan
4,49529,John Carter,"John Carter is a war-weary, former military ca...","Lost in our world, found in another.",Action Adventure Science Fiction,based on novel mars medallion space travel pri...,Taylor Kitsch Lynn Collins Samantha Morton,Andrew Stanton
...,...,...,...,...,...,...,...,...
4798,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"He didn't come looking for trouble, but troubl...",Action Crime Thriller,united statesâ€“mexico barrier legs arms paper k...,Carlos Gallardo Jaime de Hoyos Peter Marquardt,Robert Rodriguez
4799,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,A newlywed couple's honeymoon is upended by th...,Comedy Romance,,Edward Burns Kerry BishÃ© Marsha Dietlein,Edward Burns
4800,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",,Comedy Drama Romance TV Movie,date love at first sight narration investigati...,Eric Mabius Kristin Booth Crystal Lowe,Scott Smith
4801,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,A New Yorker in Shanghai,,,Daniel Henney Eliza Coupe Bill Paxton,Daniel Hsia
4802,25975,My Date with Drew,Ever since the second grade when he first saw ...,,Documentary,obsession camcorder crush dream girl,Drew Barrymore Brian Herzlinger Corey Feldman,Brian Herzlinger

In [14]:
df['Vector'] = df['overview']+df['tagline']+df['genres']+df['keywords']+df['cast'] +' '+ df['crew']
df.head()

C:\Users\DELL\AppData\Local\Temp/ipykernel_28352/629935376.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Vector'] = df['overview']+df['tagline']+df['genres']+df['keywords']+df['cast'] +' '+ df['crew']

,id,title,overview,tagline,genres,keywords,cast,crew,Vector
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,Action Adventure Fantasy Science Fiction,culture clash future space war space colony so...,Sam Worthington Zoe Saldana Sigourney Weaver,James Cameron,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.",Adventure Fantasy Action,ocean drug abuse exotic island east india trad...,Johnny Depp Orlando Bloom Keira Knightley,Gore Verbinski,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,A Plan No One Escapes,Action Adventure Crime,spy based on novel secret agent sequel mi6 bri...,Daniel Craig Christoph Waltz LÃ©a Seydoux,Sam Mendes,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,The Legend Ends,Action Crime Drama Thriller,dc comics crime fighter terrorist secret ident...,Christian Bale Michael Caine Gary Oldman,Christopher Nolan,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca...","Lost in our world, found in another.",Action Adventure Science Fiction,based on novel mars medallion space travel pri...,Taylor Kitsch Lynn Collins Samantha Morton,Andrew Stanton,"John Carter is a war-weary, former military ca..."

In [15]:
df = df[['id','title','Vector']]

In [16]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stem(text:str)->str:
    x =[]
    for i in text.split():
        x.append(ps.stem(i))
    return ' '.join(x)

In [17]:
df.Vector = df.Vector.apply(stem)
df.head(2)

c:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:5516: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

,id,title,Vector
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')
vector = cv.fit_transform(df.Vector)
vector = vector.toarray()
vector.shape

(4803, 5000)

In [22]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vector)
similarity

array([[1.        , 0.08193419, 0.03419928, ..., 0.06077371, 0.        ,
        0.        ],
       [0.08193419, 1.        , 0.04259177, ..., 0.05676567, 0.01962294,
        0.01844278],
       [0.03419928, 0.04259177, 1.        , ..., 0.01974496, 0.04095301,
        0.        ],
       ...,
       [0.06077371, 0.05676567, 0.01974496, ..., 1.        , 0.0363877 ,
        0.01709964],
       [0.        , 0.01962294, 0.04095301, ..., 0.0363877 , 1.        ,
        0.08866586],
       [0.        , 0.01844278, 0.        , ..., 0.01709964, 0.08866586,
        1.        ]])

In [23]:
def recommendation(movie:str):
    index = df[df.title == movie].index[0]
    dist = similarity[index]
    l = sorted(list(enumerate(dist)),reverse=True,key=lambda x:x[1])
    for i in l[1:6]:
        # print(df.iloc[i[0]].title)
        print(i)

In [24]:
recommendation('Batman')

(210, 0.47261170463904445)
(119, 0.4059316706811661)
(3, 0.3984095364447978)
(428, 0.3910309435028875)
(65, 0.34045882057130067)